### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by roopavsm** [petermr/pyamiimage#2]
Running this command is giving no output:

`python pyamiimage.py --text <inputfile> <outputfile>`

**Comment by petermr** [comment]
With all of us developing code we should list the `branch` and the `version` if any. 

IF there is an `argparse` then it will build a dictionary of commands but. not do anything with it. There has to be logic after `argparse`

**Comment by anuvc** [comment]
@roopavsm Do you have Tesseract installed? Try installing pyamiimage again with: `pip install --upgrade pyamiimage` and check if the problem persists.
